### PR TITLE
Update zh_CN.lang

### PR DESCRIPTION
**Pull request by bakaxyf**
Need help. I can't figure out `#NoFilter Edition`

### CODE REVIEW

**Comment by blay09** [comment]
#NoFilter is a reference to Instagram, a hashtag that is used to mark pictures with no Instagram filter applied to them.

**Comment by bakaxyf** [comment]
I am still unable to figure out. it means the book will not filter items‘ recipe that are not food?

**Comment by blay09** [comment]
The book shows ALL food recipes, no matter if you have the necessary ingredients or not.
The #NoFilter edition is basically NEI for food items only.

**Comment by bakaxyf** [comment]
I think it can be merged now. And thanks for your time :D

**Pull request merged**
